//Copy over from various new item setup files for ALL new items (but not crafting)--ONLY FINISHED PRODUCT WILL GO HERE

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////                                         //////////////////////////////////////
/////////////////////////////////////             Missing Wands               //////////////////////////////////////
/////////////////////////////////////                                         //////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////Wands
////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////


//___________________________________________________________________________
//
//
//                  Wand of Polymorph
//
//___________________________________________________________________________

//Wand of polymorph wands different in BGEE and BG2EE...Using BGEE version...
ACTION_IF !FILE_EXISTS_IN_GAME ~WAND09.ITM~ BEGIN  //wand of polymorph
  COPY ~%folder%/data/arcane_crafting/wand/WAND09.ITM~ ~override~
        SAY NAME1 @900010075     //unidentified Wand
        SAY NAME2 @900010066
        SAY UNIDENTIFIED_DESC @900010076   //unidentified generic desc
	SAY DESC @900010067
  COPY ~%folder%/data/arcane_crafting/wand/SQUIRP.itm~ ~override~    //squ claw!! Grrr
  COPY ~%folder%/data/arcane_crafting/wand/ISQUIRL.bam~ ~override~    //squ claw!! Grrr
//Icon
  COPY ~%folder%/data/arcane_crafting/wand/IWAND09.bam~ ~override~
END

//___________________________________________________________________________
//
//
//                  Wand of Wonder
//
//___________________________________________________________________________

//WAND12.itm Wand of wonder (in bg2ee as WAND12.itm, but in IWDEE and BGEE is another wand of missles...)

ACTION_IF !GAME_IS ~bg2ee eet~ BEGIN  //Req NRD, of course...
  COPY ~%folder%/data/arcane_crafting/wand/WAND12.ITM~ ~override~
        SAY NAME1 @900010075     //unidentified Wand
        SAY NAME2 @900010073
        SAY UNIDENTIFIED_DESC @900010076   //unidentified generic desc
	SAY DESC @900010074
//Icon
  COPY ~%folder%/data/arcane_crafting/wand/IWAND12.bam~ ~override~
//ADD ANIMATIONS
  COPY ~%folder%/data/arcane_crafting/wand/SPFLSRIN.bam~ ~override~
  COPY ~%folder%/data/arcane_crafting/wand/SPFLESHS.bam~ ~override~
  COPY ~%folder%/data/arcane_crafting/wand/SPARMOUR.bam~ ~override~
  COPY ~%folder%/data/arcane_crafting/wand/SPSTRENI.bam~ ~override~
  COPY ~%folder%/data/arcane_crafting/wand/SPWRDFLD.bam~ ~override~
  COPY ~%folder%/data/arcane_crafting/wand/WONDER.vvc~ ~override~
  COPY ~%folder%/data/arcane_crafting/wand/MAGRES.vvc~ ~override~
  COPY ~%folder%/data/arcane_crafting/wand/ICSTRENI.vvc~ ~override~


  ACTION_IF GAME_IS ~bgee~ THEN BEGIN   //
      COPY_EXISTING ~WAND12.ITM~ ~override~
        LPF ALTER_EFFECT INT_VAR match_opcode = 139 match_parameter1 = 14667  parameter1 = 26019 END //haste notification
        LPF ALTER_EFFECT INT_VAR match_opcode = 139 match_parameter1 = 14042  parameter1 = 26016 END //Strength Modification
        LPF ALTER_EFFECT INT_VAR match_opcode = 139 match_parameter1 = 39326  parameter1 = 25954 END //Stoneskin notification  NOt best option, check gibberlings
  END

  ACTION_IF GAME_IS ~iwdee~ THEN BEGIN   //
      COPY_EXISTING ~WAND12.ITM~ ~override~
        LPF ALTER_EFFECT INT_VAR match_opcode = 139 match_parameter1 = 14667  parameter1 = 14023 END //haste notification
  END

END   //not game is bg2ee


//___________________________________________________________________________
//
//
//                  Wand of Cloudkill
//
//___________________________________________________________________________

//WAND13.itm  Wand of Cloudkill (in BGEE and BG2EE; not in IWDEE)
ACTION_IF !FILE_EXISTS_IN_GAME ~WAND13.ITM~ BEGIN  //
  COPY ~%folder%/data/arcane_crafting/wand/WAND13.ITM~ ~override~
        SAY NAME1 @900010075     //unidentified Wand
        SAY NAME2 @900010068
        SAY UNIDENTIFIED_DESC @900010076   //unidentified generic desc
	SAY DESC @900010069
//Icon
  COPY ~%folder%/data/arcane_crafting/wand/IWAND13.bam~ ~override~

END

//WAND14.itm Web sack??? IN BG2EE , but not in other two?  Monster item???
//Not going to include for now.  Doesn't seem like it's needed

//___________________________________________________________________________
//
//
//                  Wand of Apprenti
//
//___________________________________________________________________________

//WAND15.itm Wand of Apprenti Wand created for you by your apprentices in BG2EE...
//Rechargable, but should stay in that game only. I'm going to include it in all games for the recharge code, but not make it creatable in any game (you get it from your apprentices, so...)

ACTION_IF !FILE_EXISTS_IN_GAME ~WAND15.ITM~ BEGIN  //
  COPY ~%folder%/data/arcane_crafting/wand/WAND15.ITM~ ~override~
//No frills.  Only here to avoid duplicating script and d files
END

//WAND16.itm and WAND17.itm are 'potions of icedust' in BG2EE...
//Not adding for now

//Wand99.itm Wand of magic missile in BGEE and BG2EE, not IWDEE...Not sure how to handle yet. Does more damage than typical wand of mm and description is off...
//not adding for now


//___________________________________________________________________________
//
//
//                  Wand of Armory
//
//___________________________________________________________________________
//WANDARM.itm Wand of Armory IWDEE only
ACTION_IF !FILE_EXISTS_IN_GAME ~WANDARM.ITM~ BEGIN  //
  COPY ~%folder%/data/arcane_crafting/wand/WANDARM.ITM~ ~override~
        SAY NAME1 @900010075     //unidentified Wand
        SAY NAME2 @900010077
        SAY UNIDENTIFIED_DESC @900010076   //unidentified generic desc
	SAY DESC @900010078

//Icon
  COPY ~%folder%/data/arcane_crafting/wand/IWANDARM.bam~ ~override~
//Tooltip by engine
  ACTION_IF GAME_IS ~bgee~ THEN BEGIN   //
   APPEND ~TOOLTIP.2da~ ~WANDARM%TAB%26366%TAB%26429%TAB%-1~
  END
  ACTION_IF GAME_IS ~bg2ee eet~ THEN BEGIN   //
   APPEND ~TOOLTIP.2da~ ~WANDARM%TAB%12053%TAB%12129%TAB%-1~
  END
END

//CONTINUE

//___________________________________________________________________________
//
//
//                  Wand of
//
//___________________________________________________________________________
//WANDCOR.itm Wand of Corrosion IWDEE only
ACTION_IF !FILE_EXISTS_IN_GAME ~WANDCOR.ITM~ BEGIN  //Req NRD, of course...
  COPY ~%folder%/data/arcane_crafting/wand/WANDCOR.ITM~ ~override~
        SAY NAME2 @116007
	SAY DESC @116008
//Icon
  COPY ~%folder%/data/arcane_crafting/wand/IWANDCOR.bam~ ~override~
//CONTINUE

//Tooltip by engine
  ACTION_IF GAME_IS ~bgee~ THEN BEGIN   //
   APPEND ~TOOLTIP.2da~ ~WANDARM%TAB%26366%TAB%26429%TAB%-1~
  END
  ACTION_IF GAME_IS ~bg2ee eet~ THEN BEGIN   //
   APPEND ~TOOLTIP.2da~ ~WANDARM%TAB%12053%TAB%12129%TAB%-1~
  END
END

//___________________________________________________________________________
//
//
//                  Wand of
//
//___________________________________________________________________________
//WANDFRE.itm Wand of Freezing Death IWDEE only

ACTION_IF !FILE_EXISTS_IN_GAME ~WANDFRE.ITM~ BEGIN  //
  COPY ~%folder%/data/arcane_crafting/wand/WANDFRE.ITM~ ~override~
        SAY NAME2 @116007
	SAY DESC  @116008
//Icon
  COPY ~%folder%/data/arcane_crafting/wand/IWANDCOR.bam~ ~override~
//CONTINUE

//Tooltip by engine
  ACTION_IF GAME_IS ~bgee~ THEN BEGIN   //
   APPEND ~TOOLTIP.2da~ ~WANDARM%TAB%26366%TAB%26429%TAB%-1~
  END
  ACTION_IF GAME_IS ~bg2ee eet~ THEN BEGIN   //
   APPEND ~TOOLTIP.2da~ ~WANDARM%TAB%12053%TAB%12129%TAB%-1~
  END
END

//___________________________________________________________________________
//
//
//                  Wand of
//
//___________________________________________________________________________
//WANDTRP.itm  Wand of Trap Detection


//WANDFAK.itm A second wand of lightning only in IWDEE    Fake??? Add for completenss in recharge code just in case


//WANDMIS.itm Pemby's Wand of Many Missiles: a better mm wand... IWDEE only Add for completeness in recharge code..

//WANDREA.itm another wand of lightning only in IWDEE...  Add for completenss in recharge code just in case


////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////                                         //////////////////////////////////////
/////////////////////////////////////             Missing Potions             //////////////////////////////////////
/////////////////////////////////////                                         //////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////                                         //////////////////////////////////////
/////////////////////////////////////             Missing Scrolls             //////////////////////////////////////
/////////////////////////////////////                                         //////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

