////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////                                         //////////////////////////////////////
/////////////////////////////////////            IWDEE Potions                //////////////////////////////////////
/////////////////////////////////////                                         //////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


/////////////////////////////////////////////////////\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
/////////////////////////////////////////////////////\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
////////////////////////////////            				   \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
////////////////////////////////                  COFFEE                   \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
////////////////////////////////            				   \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
/////////////////////////////////////////////////////\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
/////////////////////////////////////////////////////\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
//IWDEE potion, removes fatigue

ACTION_IF NOT FILE_EXISTS_IN_GAME ~COFFEE.itm~ BEGIN
  COPY ~%folder%/data/potions/IWDEE/COFFEE.itm~ ~override~
        SAY NAME1 @115257               //unidentified item
        SAY UNIDENTIFIED_DESC @115258   //unidentified  desc
        SAY NAME2 @115264               //identified item
        SAY DESC @115265                //identified  desc
  LPF ALTER_EFFECT INT_VAR match_opcode = 139 parameter1 = RESOLVE_STR_REF (@115261) END  //Gulp!
  //bam
  COPY ~%folder%/data/potions/BG2EE/IPOTN47.bam~ ~override~  //same bam

END

/////////////////////////////////////////////////////\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
/////////////////////////////////////////////////////\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
////////////////////////////////            				   \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
////////////////////////////////                Mummy's Tea                \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
////////////////////////////////            				   \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
/////////////////////////////////////////////////////\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
/////////////////////////////////////////////////////\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
//IWDEE potion, removes disease

ACTION_IF NOT FILE_EXISTS_IN_GAME ~ADISEASE.itm~ BEGIN
  COPY ~%folder%/data/potions/IWDEE/ADISEASE.itm~ ~override~
        SAY NAME1 @115257               //unidentified item
        SAY UNIDENTIFIED_DESC @115258   //unidentified  desc
        SAY NAME2 @115259               //identified item
        SAY DESC @115260                //identified  desc
  LPF ALTER_EFFECT INT_VAR match_opcode = 139 parameter1 = RESOLVE_STR_REF (@115261) END  //Gulp!

    //bam
  COPY ~%folder%/data/potions/IWDEE/IPOTN20.bam~ ~override~

END

/////////////////////////////////////////////////////\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
/////////////////////////////////////////////////////\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
////////////////////////////////            				   \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
////////////////////////////////           Oil of Null Effect              \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
////////////////////////////////            				   \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
/////////////////////////////////////////////////////\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
/////////////////////////////////////////////////////\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
//IWDEE potion, removes a;; magic effects

ACTION_IF NOT FILE_EXISTS_IN_GAME ~PNULL.itm~ BEGIN
  COPY ~%folder%/data/potions/IWDEE/PNULL.itm~ ~override~
        SAY NAME1 @115257               //unidentified item
        SAY UNIDENTIFIED_DESC @115258   //unidentified  desc
        SAY NAME2 @115262               //identified item
        SAY DESC @115263                //identified  desc
  LPF ALTER_EFFECT INT_VAR match_opcode = 139 parameter1 = RESOLVE_STR_REF (@115261) END  //Gulp!
    //bam
  COPY ~%folder%/data/potions/IWDEE/IPOTN49.bam~ ~override~

END

/////////////////////////////////////////////////////\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
/////////////////////////////////////////////////////\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
////////////////////////////////            				   \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
////////////////////////////////        Oil of the Serpent's Scales        \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
////////////////////////////////            				   \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
/////////////////////////////////////////////////////\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
/////////////////////////////////////////////////////\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
//

ACTION_IF NOT FILE_EXISTS_IN_GAME ~SERPSCA.itm~ BEGIN
  COPY ~%folder%/data/potions/IWDEE/SERPSCA.itm~ ~override~
        SAY NAME1 @115257               //unidentified item
        SAY UNIDENTIFIED_DESC @115258   //unidentified  desc
        SAY NAME2 @900000042               //identified item
        SAY DESC @900000043                //identified  desc
  LPF ALTER_EFFECT INT_VAR match_opcode = 139 parameter1 = RESOLVE_STR_REF (@115261) END  //Gulp!
    //bam
  COPY ~%folder%/data/potions/IWDEE/IMISC76.bam~ ~override~

END

/////////////////////////////////////////////////////\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
/////////////////////////////////////////////////////\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
////////////////////////////////            				   \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
////////////////////////////////           Elven Healing Wine              \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
////////////////////////////////            				   \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
/////////////////////////////////////////////////////\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
/////////////////////////////////////////////////////\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
//

ACTION_IF NOT FILE_EXISTS_IN_GAME ~ELFWINE.itm~ BEGIN
  COPY ~%folder%/data/potions/IWDEE/ELFWINE.itm~ ~override~
        SAY NAME1 @900000052            //unidentified item
        SAY UNIDENTIFIED_DESC @900000053 //unidentified  desc
        SAY NAME2 @900000044               //identified item
        SAY DESC @900000045                //identified  desc
  LPF ALTER_EFFECT INT_VAR match_opcode = 139 parameter1 = RESOLVE_STR_REF (@115261) END  //Gulp!
    //bam
  COPY ~%folder%/data/potions/IWDEE/IMISC61.bam~ ~override~

END

/////////////////////////////////////////////////////\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
/////////////////////////////////////////////////////\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
////////////////////////////////            				   \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
////////////////////////////////           Philter of Purification         \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
////////////////////////////////            				   \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
/////////////////////////////////////////////////////\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
/////////////////////////////////////////////////////\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
//

ACTION_IF NOT FILE_EXISTS_IN_GAME ~PHILTER.itm~ BEGIN
  COPY ~%folder%/data/potions/IWDEE/PHILTER.itm~ ~override~
        SAY NAME1 @115257               //unidentified item
        SAY UNIDENTIFIED_DESC @115258   //unidentified  desc
        SAY NAME2 @900000048               //identified item
        SAY DESC @900000049                //identified  desc
  LPF ALTER_EFFECT INT_VAR match_opcode = 139 parameter1 = RESOLVE_STR_REF (@115261) END  //Gulp!
    //bam
  COPY ~%folder%/data/potions/IWDEE/IPOTN20.bam~ ~override~

END

/////////////////////////////////////////////////////\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
/////////////////////////////////////////////////////\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
////////////////////////////////            				   \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
////////////////////////////////           Oil of Second Chances           \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
////////////////////////////////            				   \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
/////////////////////////////////////////////////////\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
/////////////////////////////////////////////////////\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
//

ACTION_IF NOT FILE_EXISTS_IN_GAME ~CHANCE.itm~ BEGIN
  COPY ~%folder%/data/potions/IWDEE/CHANCE.itm~ ~override~
        SAY NAME1 @115257               //unidentified item
        SAY UNIDENTIFIED_DESC @115258   //unidentified  desc
        SAY NAME2 @900000050               //identified item
        SAY DESC @900000051                //identified  desc
  LPF ALTER_EFFECT INT_VAR match_opcode = 139 parameter1 = RESOLVE_STR_REF (@115261) END  //Gulp!
    //bam
  COPY ~%folder%/data/potions/IWDEE/ICHANCE.bam~ ~override~

END

/////////////////////////////////////////////////////\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
/////////////////////////////////////////////////////\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
////////////////////////////////            				   \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
////////////////////////////////                Spirit Essence             \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
////////////////////////////////            				   \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
/////////////////////////////////////////////////////\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
/////////////////////////////////////////////////////\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
//

ACTION_IF NOT FILE_EXISTS_IN_GAME ~SPIRIT.itm~ BEGIN
  COPY ~%folder%/data/potions/IWDEE/SPIRIT.itm~ ~override~
        SAY NAME1 @115257               //unidentified item
        SAY UNIDENTIFIED_DESC @115258   //unidentified  desc
        SAY NAME2 @900000052               //identified item
        SAY DESC @900000053                //identified  desc
  LPF ALTER_EFFECT INT_VAR match_opcode = 139 parameter1 = RESOLVE_STR_REF (@115261) END  //Gulp!
    //bam
  COPY ~%folder%/data/potions/IWDEE/ISPIRIT.bam~ ~override~

END

/////////////////////////////////////////////////////\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
/////////////////////////////////////////////////////\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
////////////////////////////////            				   \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
////////////////////////////////        Potion of Action Transference      \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
////////////////////////////////            				   \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
/////////////////////////////////////////////////////\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
/////////////////////////////////////////////////////\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
//IWDEE potion, +1 Cha, -1 Dex
//prob won't include

/////////////////////////////////////////////////////\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
/////////////////////////////////////////////////////\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
////////////////////////////////            				   \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
////////////////////////////////        Potion of Holy Transference        \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
////////////////////////////////            				   \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
/////////////////////////////////////////////////////\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
/////////////////////////////////////////////////////\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
//IWDEE potion, +2 Wis, -1 Dex
//prob won't include


////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////                                         //////////////////////////////////////
/////////////////////////////////////             SOD Potions                 //////////////////////////////////////
/////////////////////////////////////                                         //////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

/////////////////////////////////////////////////////\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
/////////////////////////////////////////////////////\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
////////////////////////////////            				   \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
////////////////////////////////           Potion of Persuasiveness        \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
////////////////////////////////            				   \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
/////////////////////////////////////////////////////\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
/////////////////////////////////////////////////////\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
//IWDEE potion, removes a;; magic effects

ACTION_IF NOT FILE_EXISTS_IN_GAME ~POTN60.itm~ BEGIN
  COPY ~%folder%/data/arcane_crafting/potions/SOD/POTN60.itm~ ~override~
        SAY NAME1 @115257               //unidentified item
        SAY UNIDENTIFIED_DESC @115258   //unidentified  desc
        SAY NAME2 @900000036               //identified item
        SAY DESC @900000037                //identified  desc
  LPF ALTER_EFFECT INT_VAR match_opcode = 139 parameter1 = RESOLVE_STR_REF (@115261) END  //Gulp!

  //bam
  COPY ~%folder%/data/potions/SOD/IBDPTN60.bam~ ~override~

END

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////                                         //////////////////////////////////////
/////////////////////////////////////             BG2EE Potions               //////////////////////////////////////
/////////////////////////////////////                                         //////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

/////////////////////////////////////////////////////\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
/////////////////////////////////////////////////////\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
////////////////////////////////            				   \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
////////////////////////////////                Brine Potion               \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
////////////////////////////////            				   \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
/////////////////////////////////////////////////////\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
/////////////////////////////////////////////////////\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
//MISC9Y.itm Shoud I include?

/*
ACTION_IF NOT FILE_EXISTS_IN_GAME ~MISC9Y.itm~ BEGIN
  COPY ~%folder%/data/arcane_crafting/potions/SOD/POTN60.itm~ ~override~
        SAY NAME1 @115257               //unidentified item
        SAY UNIDENTIFIED_DESC @115258   //unidentified  desc
        SAY NAME2 @900000036               //identified item
        SAY DESC @900000037                //identified  desc
  LPF ALTER_EFFECT INT_VAR match_opcode = 139 parameter1 = RESOLVE_STR_REF (@115261) END  //Gulp!

  //bam
  COPY ~%folder%/data/arcane_crafting/potions/SOD/IBDPTN60.bam~ ~override~

END
*/

/////////////////////////////////////////////////////\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
/////////////////////////////////////////////////////\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
////////////////////////////////            				   \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
////////////////////////////////         Potion of Superior Healing        \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
////////////////////////////////            				   \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
/////////////////////////////////////////////////////\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
/////////////////////////////////////////////////////\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
//IWDEE potion, removes a;; magic effects

ACTION_IF NOT FILE_EXISTS_IN_GAME ~POTN55.itm~ BEGIN
  COPY ~%folder%/data/arcane_crafting/potions/BG2EE/POTN55.itm~ ~override~
        SAY NAME1 @115257               //unidentified item
        SAY UNIDENTIFIED_DESC @115258   //unidentified  desc
        SAY NAME2 @900000038               //identified item
        SAY DESC @900000039                //identified  desc
  LPF ALTER_EFFECT INT_VAR match_opcode = 139 parameter1 = RESOLVE_STR_REF (@115261) END  //Gulp!

  //bam
  COPY ~%folder%/data/potions/BG2EE/IPOTN55.bam~ ~override~

END

/////////////////////////////////////////////////////\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
/////////////////////////////////////////////////////\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
////////////////////////////////            				   \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
////////////////////////////////             Potion of Barkskin            \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
////////////////////////////////            				   \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
/////////////////////////////////////////////////////\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
/////////////////////////////////////////////////////\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
//

ACTION_IF NOT FILE_EXISTS_IN_GAME ~OHBPTN01.itm~ BEGIN
  COPY ~%folder%/data/arcane_crafting/potions/BG2EE/OHBPTN01.itm~ ~override~
        SAY NAME1 @115257               //unidentified item
        SAY UNIDENTIFIED_DESC @115258   //unidentified  desc
        SAY NAME2 @900000040               //identified item
        SAY DESC @900000041                //identified  desc
  LPF ALTER_EFFECT INT_VAR match_opcode = 139 parameter1 = RESOLVE_STR_REF (@115261) END  //Gulp!

  //bam
  COPY ~%folder%/data/potions/BG2EE/IPOTN47.bam~ ~override~

END

/////////////////////////////////////////////////////\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
/////////////////////////////////////////////////////\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
////////////////////////////////            				   \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
////////////////////////////////           Potion of Clairvoyance          \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
////////////////////////////////            				   \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
/////////////////////////////////////////////////////\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
/////////////////////////////////////////////////////\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
//

ACTION_IF NOT FILE_EXISTS_IN_GAME ~OHDPOTN1.itm~ BEGIN
  COPY ~%folder%/data/arcane_crafting/potions/BG2EE/OHDPOTN1.itm~ ~override~
        SAY NAME1 @115257               //unidentified item
        SAY UNIDENTIFIED_DESC @115258   //unidentified  desc
        SAY NAME2 @900000046               //identified item
        SAY DESC @900000047                //identified  desc
  LPF ALTER_EFFECT INT_VAR match_opcode = 139 parameter1 = RESOLVE_STR_REF (@115261) END  //Gulp!

  //bam
  COPY ~%folder%/data/potions/BG2EE/IPOTN47.bam~ ~override~

END


/*


////////////////////////////////////////////////////////////////////////
//////////////////           Miscellaneous            //////////////////
////////////////////////////////////////////////////////////////////////

//ground bam
ACTION_IF NOT FILE_EXISTS_IN_GAME ~GWAND01.bam~ BEGIN
  COPY ~%folder%/data/arcane_crafting/wand/GWAND01.bam~ ~override~
END

//missing gems (not nec for first draft, but I'll leave it because why not?)
ACTION_IF NOT FILE_EXISTS_IN_GAME ~MISC41.itm~ BEGIN
  COPY ~%folder%/data/arcane_crafting/wand/MISC41.itm~ ~override~
        SAY NAME1 @68087
        SAY NAME2 @68088
	SAY DESC @68089
END

ACTION_IF NOT FILE_EXISTS_IN_GAME ~TTTREAS.itm~ BEGIN
  COPY ~%folder%/data/arcane_crafting/wand/TTTREAS.itm~ ~override~
        SAY NAME1 @68087
        SAY NAME2 @68088
	SAY DESC @68089
END

////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////                                    ////////////////////////////////////
////////////////////////////////////          Tier I Wands              ////////////////////////////////////
////////////////////////////////////                                    ////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////





//___________________________________________________________________________
//
//
//                  Mistletoe
//
//___________________________________________________________________________

//| Mistletoe (N)  | I |  Shillelagh |

ACTION_IF NOT FILE_EXISTS_IN_GAME ~B_WAN03.ITM~ BEGIN

  COPY ~%folder%/data/wands/B_WAN03.itm~ ~override~
        SAY NAME1 @900010075     //unidentified Wand
        SAY UNIDENTIFIED_DESC @900010076   //unidentified generic desc
        SAY NAME2 @900010005
        SAY DESC @900010006
END


//___________________________________________________________________________
//
//
//                  Wand of Fear
//
//___________________________________________________________________________
// WAND02.itm (only one, and present in all engines)

//___________________________________________________________________________
//
//
//                  Wand of Fog
//
//___________________________________________________________________________
////////////////////////////////////////////////////////////////////////
//| of Fog (Ns) | I |  as Obscuring Mist |
//only installed if SR is installed, but add a dummy for code

//cleric version

ACTION_IF NOT FILE_EXISTS_IN_GAME ~B_WAN11.ITM~ BEGIN
 ACTION_IF (FILE_CONTAINS_EVALUATED(~spell.ids~ ~CLERIC_OBSCURING_MIST~)) BEGIN  //SR obscuring Mist
//copy the spell
 LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~CLERIC_OBSCURING_MIST~
  RET spell_res
 END
 COPY_EXISTING ~%spell_res%.spl~ ~override/B_WANFG.spl~
  WRITE_BYTE 0x001c  4  //innate
 END   //if Obscuring mist is not in game

 ACTION_IF (!FILE_CONTAINS_EVALUATED(~spell.ids~ ~CLERIC_OBSCURING_MIST~)) BEGIN
 //addspell a dummy spell and then save it as B_WANFG.spl
 COPY_EXISTING ~SPWI112.spl~ ~override/B_WANFG.spl~
   ADD_SPELL ~override/B_WANFG.spl~ 1 1 ~CLERIC_OBSCURING_MIST~ //
     LPF ALTER_SPELL_TYPE
         STR_VAR spell_type = 1 //spell type: Wizard making it unusable as cleric spell
     END
 END //if obscuring mist not in game

//actual wand

  COPY ~%folder%/data/wands/B_WAN11.itm~ ~override~
        SAY NAME1 @900010075     //unidentified Wand
        SAY UNIDENTIFIED_DESC @900010076   //unidentified generic desc
        SAY NAME2 @900010021
        SAY DESC @900010022

END   //Not Wand of Fog in game

//wiz version

ACTION_IF NOT FILE_EXISTS_IN_GAME ~B_WAN20.ITM~ BEGIN
 ACTION_IF (FILE_CONTAINS_EVALUATED(~spell.ids~ ~WIZARD_OBSCURING_MIST~)) BEGIN  //SR obscuring Mist
//copy the spell
 LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~WIZARD_OBSCURING_MIST~
  RET spell_res
 END
 COPY_EXISTING ~%spell_res%.spl~ ~override/B_WANFO.spl~
  WRITE_BYTE 0x001c  4  //innate
 END   //if Obscuring mist is not in game

 ACTION_IF (!FILE_CONTAINS_EVALUATED(~spell.ids~ ~WIZARD_OBSCURING_MIST~)) BEGIN
 //addspell a dummy spell and then save it as B_WANFO.spl
 COPY_EXISTING ~SPWI112.spl~ ~override/B_WANFG.spl~
   ADD_SPELL ~override/B_WANFG.spl~ 2 1 ~WIZARD_OBSCURING_MIST~ //
     LPF ALTER_SPELL_TYPE
         STR_VAR spell_type = 2 //spell type: Cleric making it unusable as wizard spell
     END
 END //if obscuring mist not in game

//actual wand

  COPY ~%folder%/data/wands/B_WAN20.itm~ ~override~
        SAY NAME1 @900010075     //unidentified Wand
        SAY UNIDENTIFIED_DESC @900010076   //unidentified generic desc
        SAY NAME2 @900010021
        SAY DESC @900010079

END   //Not Wand of Fog in game

/*
//now, include in tier 1 wands:
    COPY ~%folder%/lib/wand_lists/wand_tier_list.tpa~ ~%folder%/lib/wand_lists/wand_tier_list.tpa~
      REPLACE_TEXTUALLY ~//B_WAN11~ ~B_WAN11~

*/


//___________________________________________________________________________
//
//
//                  Wand of Freshness
//
//___________________________________________________________________________
//| of Freshness (N) | I |  as ZoSA (or gust of wind if SR) | p235

ACTION_IF NOT FILE_EXISTS_IN_GAME ~B_WAN10.ITM~ BEGIN
  COPY ~%folder%/data/wands/B_WAN10.itm~ ~override~
        SAY NAME1 @900010075     //unidentified Wand
        SAY UNIDENTIFIED_DESC @900010076   //unidentified generic desc
        SAY NAME2 @900010019
        SAY DESC @900010020
END


//___________________________________________________________________________
//
//
//                  Wand of Illumination
//
//___________________________________________________________________________
//| of Illumination (N) | I | 6d6 to undead (only) |
//just use the fireball pro...

//wiz versioni
ACTION_IF NOT FILE_EXISTS_IN_GAME ~B_WAN19.itm~ BEGIN

  COPY ~%folder%/data/wands/B_WAN19.itm~ ~override~
        SAY NAME1 @900010075     //unidentified Wand
        SAY UNIDENTIFIED_DESC @900010076   //unidentified generic desc
        SAY NAME2 @900010037
        SAY DESC @900010038

END

//pri versioni
ACTION_IF NOT FILE_EXISTS_IN_GAME ~B_WAN22.itm~ BEGIN
  LPF ALTER_EFFECT INT_VAR duration = 30 END  //duration 1 turn

  COPY ~%folder%/data/wands/B_WAN22.itm~ ~override~
        SAY NAME1 @900010075     //unidentified Wand
        SAY UNIDENTIFIED_DESC @900010076   //unidentified generic desc
        SAY NAME2 @900010037
        SAY DESC @900010083

END

//___________________________________________________________________________
//
//
//                  Wand of Peace
//
//___________________________________________________________________________
//| of Peace  | I | Sanctuary; protection from evil; protection from evil 10' |

/* Just not ready yet
ACTION_IF NOT FILE_EXISTS_IN_GAME ~B_WAN25.itm~ BEGIN
//remove fear allies
 COPY_EXISTING ~SPPR108.spl~ ~override/B_WANR1.spl~
        SAY NAME1 @900010090     //
        SAY NAME2 @900010090

//no attack (enemies) Is this possible? Maybe the wand removes fear and gives target sanctuary. If so, move to a higher tier...

//CONTINUE

  COPY ~%folder%/data/wands/B_WANR1.spl~ ~override~
        SAY NAME1 @900010090     //
        SAY NAME2 @900010090

  COPY ~%folder%/data/wands/B_WAN25.itm~ ~override~
        SAY NAME1 @900010075     //unidentified Wand
        SAY UNIDENTIFIED_DESC @900010076   //unidentified generic desc
        SAY NAME2 @900010088
        SAY DESC @900010089

END
*/

//___________________________________________________________________________
//
//
//                  Wand of Teeth
//
//___________________________________________________________________________
//| of Teeth (N)  | I | 2d6+2 missile dam (save 1/2) |
ACTION_IF NOT FILE_EXISTS_IN_GAME ~B_WAN01.ITM~ BEGIN
  COPY ~%folder%/data/wands/B_WAN01.itm~ ~override~
        SAY NAME1 @900010075     //unidentified Wand
        SAY UNIDENTIFIED_DESC @900010076   //unidentified generic desc
        SAY NAME2 @900010001
        SAY DESC @900010002
END

//___________________________________________________________________________
//
//
//                  Wand of Trap Detection
//
//___________________________________________________________________________
//| of Trap Detection (N)  | I |  |

/// Wizard version

//WANDTRP.itm  Wand of Trap Detection iwdee
ACTION_IF NOT FILE_EXISTS_IN_GAME ~WANDTRP.itm~ BEGIN
  COPY ~%folder%/data/wands/WANDTRP.itm~ ~override~
        SAY NAME1 @900010075     //unidentified Wand
        SAY UNIDENTIFIED_DESC @900010076   //unidentified generic desc
        SAY NAME2 @900010080
        SAY DESC @900010081
END

/// Priest version
ACTION_IF NOT FILE_EXISTS_IN_GAME ~B_WAN21.itm~ BEGIN
  COPY ~%folder%/data/wands/B_WAN21.itm~ ~override~
        SAY NAME1 @900010075     //unidentified Wand
        SAY UNIDENTIFIED_DESC @900010076   //unidentified generic desc
        SAY NAME2 @900010080
        SAY DESC @900010082
END

//bam
ACTION_IF NOT FILE_EXISTS_IN_GAME ~IWANDTRP.bam~ BEGIN
  COPY ~%folder%/data/wands/IWANDTRP.bam~ ~override~
END


////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////                                    ////////////////////////////////////
////////////////////////////////////         Tier II Wands              ////////////////////////////////////
////////////////////////////////////                                    ////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////


//___________________________________________________________________________
//
//
//                  Wand of Armory
//
//___________________________________________________________________________
//WANDARM.itm Wand of Armory IWDEE only
ACTION_IF !FILE_EXISTS_IN_GAME ~WANDARM.ITM~ BEGIN  //
  COPY ~%folder%/data/arcane_crafting/wand/WANDARM.ITM~ ~override~
        SAY NAME1 @900010075     //unidentified Wand
        SAY NAME2 @900010077
        SAY UNIDENTIFIED_DESC @900010076   //unidentified generic desc
	SAY DESC @900010078

//Icon
  COPY ~%folder%/data/arcane_crafting/wand/IWANDARM.bam~ ~override~
//Tooltip by engine
 ACTION_IF GAME_IS ~bgee~ THEN BEGIN   //
   APPEND ~TOOLTIP.2da~ ~WANDARM%TAB%26366%TAB%26429%TAB%-1~
 END
 ACTION_IF GAME_IS ~bg2ee eet~ THEN BEGIN   //
   APPEND ~TOOLTIP.2da~ ~WANDARM%TAB%12053%TAB%12129%TAB%-1~
 END
END

//___________________________________________________________________________
//
//
//                  Wand of Force
//
//___________________________________________________________________________
//| of Force (N) | II |  2d6 crush damage and Push away cre (save 1/2 dam and no push) |
ACTION_IF NOT FILE_EXISTS_IN_GAME ~B_WAN08.ITM~ BEGIN
//pro
  ADD_PROJECTILE ~%folder%/data/wands/IDPRO230.pro~   //projectile
// bam
  COPY ~%folder%/data/wands/NECROT.bam~ ~override~
  COPY ~%folder%/data/wands/IWAND01.bam~ ~override~

//wav
  COPY ~%folder%/data/wands/RED05.WAV~ ~override~
  COPY ~%folder%/data/wands/#TRA_02.WAV~ ~override~

  COPY ~%folder%/data/wands/B_WAN08.itm~ ~override~
        SAY NAME1 @900010075                //unidentified Wand
        SAY UNIDENTIFIED_DESC @900010076   //unidentified wand generic desc
        SAY NAME2 @900010015
        SAY DESC @900010016
  LPF ALTER_ITEM_HEADER INT_VAR projectile = %IDPRO230% END
END

//___________________________________________________________________________
//
//
//                  Wand of Knock
//
//___________________________________________________________________________
//| of Knock(N) | II | As Knock |   p237
ACTION_IF NOT FILE_EXISTS_IN_GAME ~B_WAN02.ITM~ BEGIN
  COPY ~%folder%/data/wands/B_WAN02.itm~ ~override~
        SAY NAME1 @900010075                //unidentified Wand
        SAY UNIDENTIFIED_DESC @900010076   //unidentified wand generic desc
        SAY NAME2 @900010003
        SAY DESC @900010004
END

//___________________________________________________________________________
//
//
//                  Wand of Magic Missiles
//
//___________________________________________________________________________

//for recharge code, but not creation (except the basic one for standard)
//creation uses WAND03

ACTION_IF NOT FILE_EXISTS_IN_GAME ~WAND12.ITM~ BEGIN

  COPY_EXISTING ~WAND03.ITM~ ~override/WAND12.ITM~

END

ACTION_IF NOT FILE_EXISTS_IN_GAME ~LIGHT.ITM~ BEGIN

  COPY_EXISTING ~WAND03.ITM~ ~override/LIGHT.ITM~

END

ACTION_IF NOT FILE_EXISTS_IN_GAME ~PULS01.ITM~ BEGIN

  COPY_EXISTING ~WAND03.ITM~ ~override/PULS01.ITM~

END

ACTION_IF NOT FILE_EXISTS_IN_GAME ~PULS02.ITM~ BEGIN

  COPY_EXISTING ~WAND03.ITM~ ~override/PULS02.ITM~

END

ACTION_IF NOT FILE_EXISTS_IN_GAME ~WANDMIS.ITM~ BEGIN

  COPY_EXISTING ~WAND03.ITM~ ~override/WANDMIS.itm~

END

ACTION_IF NOT FILE_EXISTS_IN_GAME ~WAND99.ITM~ BEGIN

  COPY_EXISTING ~WAND03.ITM~ ~override/WAND99.itm~

END

////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////                                    ////////////////////////////////////
////////////////////////////////////         Tier III Wands             ////////////////////////////////////
////////////////////////////////////                                    ////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////

//___________________________________________________________________________
//
//
//                  Bonewand
//
//___________________________________________________________________________
//| Bonewand  (N) | III | Shards of Bone (6d4 piercing dam save for 1/2); Animate Dead as Spell |

//wiz
ACTION_IF NOT FILE_EXISTS_IN_GAME ~B_WAN07.ITM~ BEGIN
//Projectile
  ADD_PROJECTILE ~%folder%/data/iwd_spells/priest_4/idpro303.pro~   //projectile
//probam
  COPY ~%folder%/data/iwd_spells/priest_4/TSPRAYT.bam~ ~override~   //
  COPY ~%folder%/data/wands/B_WAN07.itm~ ~override~
        SAY NAME1 @900010075     //unidentified Wand
        SAY UNIDENTIFIED_DESC @900010076   //unidentified generic desc
        SAY NAME2 @900010013
        SAY DESC @900010014
  LPF ALTER_ITEM_HEADER
    INT_VAR  header = 1 projectile = %idpro303%
  END
//tooltip
 LAF tooltips INT_VAR
  $tip(1) = RESOLVE_STR_REF (@900010039) // Boneshard
  $tip(2) = RESOLVE_STR_REF (@900010040) // Animate Skeleton Warrior
 STR_VAR
  item = B_WAN07 // file name
 END

  COPY ~%folder%/data/wands/B_WAN23.itm~ ~override~
        SAY NAME1 @900010075     //unidentified Wand
        SAY UNIDENTIFIED_DESC @900010076   //unidentified generic desc
        SAY NAME2 @900010013
        SAY DESC @900010014
  LPF ALTER_ITEM_HEADER
    INT_VAR  header = 1 projectile = %idpro303%
  END
//tooltip
 LAF tooltips INT_VAR
  $tip(1) = RESOLVE_STR_REF (@900010039) // Boneshard
  $tip(2) = RESOLVE_STR_REF (@900010040) // Animate Skeleton Warrior
 STR_VAR
  item = B_WAN23 // file name
 END

END

//___________________________________________________________________________
//
//
//                  Wand of Fireballs
//
//___________________________________________________________________________
//| of Fireballs (N) | III | As Fireball Spell | 6d6 dam

ACTION_IF NOT FILE_EXISTS_IN_GAME ~B_WAN05.ITM~ BEGIN

  COPY ~%folder%/data/wands/B_WAN05.itm~ ~override~
        SAY NAME1 @900010075     //unidentified Wand
        SAY UNIDENTIFIED_DESC @900010076   //unidentified generic desc
        SAY NAME2 @900010009
        SAY DESC @900010010
END

//___________________________________________________________________________
//
//
//                  Wand of Lightning
//
//___________________________________________________________________________

ACTION_IF NOT FILE_EXISTS_IN_GAME ~IWAND07.BAM~ BEGIN

  COPY ~%folder%/data/arcane_crafting/wand/IWAND07.BAM~ ~override~

END


ACTION_IF NOT FILE_EXISTS_IN_GAME ~WAND07.ITM~ BEGIN

  COPY ~%folder%/data/arcane_crafting/wand/WAND07.ITM~ ~override~
        SAY NAME1 @900010055
        SAY NAME2 @900010056
	SAY DESC @900010057
        SAY UNIDENTIFIED_DESC @900010058

END

//recharge only
ACTION_IF NOT FILE_EXISTS_IN_GAME ~MISC7N.ITM~ BEGIN

  COPY ~%folder%/data/arcane_crafting/wand/WAND07.ITM~ ~override/MISC7N.ITM~
        SAY NAME1 @900010055
        SAY NAME2 @900010056
	SAY DESC @900010057
        SAY UNIDENTIFIED_DESC @900010058

END

//recharge only
//WANDREA.itm another wand of lightning only in IWDEE...  Add for completenss in recharge code just in case
ACTION_IF NOT FILE_EXISTS_IN_GAME ~WANDREA.ITM~ BEGIN

  COPY ~%folder%/data/arcane_crafting/wand/WAND07.ITM~ ~override/WANDREA.ITM~
        SAY NAME1 @900010055
        SAY NAME2 @900010056
	SAY DESC @900010057
        SAY UNIDENTIFIED_DESC @900010058

END

//recharge only
//WANDFAK.itm A second wand of lightning only in IWDEE    Fake??? Add for completenss in recharge code just in case
ACTION_IF NOT FILE_EXISTS_IN_GAME ~WANDFAK.ITM~ BEGIN

  COPY ~%folder%/data/arcane_crafting/wand/WAND07.ITM~ ~override/WANDFAK.ITM~
        SAY NAME1 @900010055
        SAY NAME2 @900010056
	SAY DESC @900010057
        SAY UNIDENTIFIED_DESC @900010058

END


////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////                                    ////////////////////////////////////
////////////////////////////////////          Tier IV Wands             ////////////////////////////////////
////////////////////////////////////                                    ////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////

//___________________________________________________________________________
//
//
//                  Wand of Arc Lightning
//
//___________________________________________________________________________



ACTION_IF NOT FILE_EXISTS_IN_GAME ~B_WAN24.ITM~ BEGIN
//projectile
ADD_PROJECTILE ~%folder%/data/arcane_crafting/wand/B_EAR01.pro~   //pro


  COPY ~%folder%/data/arcane_crafting/wand/B_WAN24.ITM~ ~override~
        SAY NAME1 @900010075     //unidentified Wand
        SAY UNIDENTIFIED_DESC @900010076   //unidentified generic desc
        SAY NAME2 @900010084
	SAY DESC @900010085
        LPF ALTER_ITEM_HEADER INT_VAR header = 2 projectile = %B_EAR01% STR_VAR END
//tooltip
 LAF tooltips INT_VAR
  $tip(1) = RESOLVE_STR_REF (@900010087) // Lightning Bolt
  $tip(2) = RESOLVE_STR_REF (@900010086) // Arc Lightning
 STR_VAR
  item = B_WAN24 // file name
 END
END

//___________________________________________________________________________
//
//
//                  Wand of Eyes
//
//___________________________________________________________________________
//| of Eyes (N) | IV |   Wizard Eye;  |  b_wan09
//add protection from B_WAND09 to WIzEye spell

ACTION_IF NOT FILE_EXISTS_IN_GAME ~B_WAN09.ITM~ BEGIN
//WIzEye
//copy wiz eye, add immunity to secspell:
  COPY_EXISTING ~SPWI425.spl~ ~override~
  LPF CLONE_EFFECT INT_VAR multi_match = 1 match_opcode = 206 STR_VAR resource = ~B_WNDEY~ END  //Protection from secspell
//create secspell
  COPY_EXISTING ~SPWI425.spl~ ~override/B_WNDEY.spl~
    WRITE_BYTE 0x001c  4  //innate no wiz spell!

//CureBlind

//Detect Invisibility
//create secspell
  COPY_EXISTING ~SPWI203.spl~ ~override/B_WNDDI.spl~
    WRITE_BYTE 0x001c  4  //innate no wiz spell!

//actual wand

  COPY ~%folder%/data/wands/B_WAN09.itm~ ~override~
        SAY NAME1 @900010075     //unidentified Wand
        SAY UNIDENTIFIED_DESC @900010076   //unidentified generic desc
        SAY NAME2 @900010017
        SAY DESC @900010018

//tooltip
 LAF tooltips INT_VAR
  $tip(1) = RESOLVE_STR_REF (@900010044) // Wizard Eye
  $tip(2) = RESOLVE_STR_REF (@900010045) // Remove Blindness
  $tip(3) = RESOLVE_STR_REF (@900010046) // Detect Invisibility
 STR_VAR
  item = B_WAN09 // file name
 END
END  //no B_WAN07.itm

//___________________________________________________________________________
//
//
//                  Wand of Polymorph
//
//___________________________________________________________________________

//Wand of polymorph wands different in BGEE and BG2EE...Using BGEE version...
ACTION_IF !FILE_EXISTS_IN_GAME ~WAND09.ITM~ BEGIN  //wand of polymorph
ACTION_IF NOT FILE_EXISTS_IN_GAME ~IWAND09.BAM~ BEGIN

  COPY ~%folder%/data/arcane_crafting/wand/IWAND09.BAM~ ~override~

END
  COPY ~%folder%/data/arcane_crafting/wand/WAND09.ITM~ ~override~
        SAY NAME1 @900010075     //unidentified Wand
        SAY NAME2 @900010066
        SAY UNIDENTIFIED_DESC @900010076   //unidentified generic desc
	SAY DESC @900010067
  COPY ~%folder%/data/arcane_crafting/wand/SQUIRP.itm~ ~override~    //squ claw!! Grrr
  COPY ~%folder%/data/arcane_crafting/wand/ISQUIRL.bam~ ~override~    //squ claw!! Grrr
//Icon
  COPY ~%folder%/data/arcane_crafting/wand/IWAND09.bam~ ~override~
END

//___________________________________________________________________________
//
//
//                  Wand of Spiders
//
//___________________________________________________________________________
//| of Spiders (N) | ? |  Spider Spawn; Summon Monster II or III | check BGEE for SPIDGISU.cre

ACTION_IF NOT FILE_EXISTS_IN_GAME ~B_WAN14.ITM~ BEGIN
  COPY ~%folder%/data/wands/B_WAN14.itm~ ~override~
        SAY NAME2 @900010027
        SAY DESC @900010028

 //tooltip
 LAF tooltips INT_VAR
  $tip(1) = RESOLVE_STR_REF (@900010047) // Summon Giant Spider
  $tip(2) = RESOLVE_STR_REF (@900010048) // Web
 STR_VAR
  item = B_WAN14 // file name
 END
END

////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////                                    ////////////////////////////////////
////////////////////////////////////          Tier V Wands              ////////////////////////////////////
////////////////////////////////////                                    ////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////

//___________________________________________________________________________
//
//
//                  Wand of Apprenti
//
//___________________________________________________________________________

//WAND15.itm Wand of Apprenti Wand created for you by your apprentices in BG2EE...
//Rechargable, but should stay in that game only. I'm going to include it in all games for the recharge code, but not make it creatable in any game (you get it from your apprentices, so...)

ACTION_IF !FILE_EXISTS_IN_GAME ~WAND15.ITM~ BEGIN  //
  COPY ~%folder%/data/arcane_crafting/wand/WAND15.ITM~ ~override~
//No frills.  Only here to avoid duplicating script and d files
END



//___________________________________________________________________________
//
//
//                  Wand of Cloudkill
//
//___________________________________________________________________________

//WAND13.itm  Wand of Cloudkill (in BGEE and BG2EE; not in IWDEE)
ACTION_IF !FILE_EXISTS_IN_GAME ~WAND13.ITM~ BEGIN  //
  COPY ~%folder%/data/arcane_crafting/wand/WAND13.ITM~ ~override~
        SAY NAME1 @900010075     //unidentified Wand
        SAY NAME2 @900010068
        SAY UNIDENTIFIED_DESC @900010076   //unidentified generic desc
	SAY DESC @900010069
//Icon
  COPY ~%folder%/data/arcane_crafting/wand/IWAND13.bam~ ~override~

END

//___________________________________________________________________________
//
//
//                  Wand of Freezing Death
//
//___________________________________________________________________________
//WANDFRE.itm Wand of Freezing Death No longer iwdee only

ACTION_IF !FILE_EXISTS_IN_GAME ~WANDFRE.ITM~ BEGIN  //
  COPY ~%folder%/data/data/wands/WANDFRE.ITM~ ~override~
        SAY NAME1 @900010075     //unidentified Wand
        SAY UNIDENTIFIED_DESC @900010076   //unidentified wand generic desc
        SAY NAME2 @900010093
	SAY DESC  @900010094
//Icon
  COPY ~%folder%/data/arcane_crafting/wand/IWANDFRE.bam~ ~override~
//Icelance
//Projectile
  ADD_PROJECTILE ~%folder%/data/wands/IDPRO251.pro~   //projectile
//bam
  COPY ~%folder%/data/wands/ICELANT.BAM~ ~override~   //animation icelant  ILNCE
  COPY ~%folder%/data/wands/ILNCE.BAM~ ~override~   //animation icelant

//sounds
  COPY ~%folder%/data/wands/#TRA_19.WAV~ ~override~   //animation
//////Spell Itself (and spell biz (e.g. sec spells)
  COPY ~%folder%/data/wands/B_LAICE.SPL~ ~override~   //b_laice
        SAY NAME1 @900010095     //
        SAY NAME2 @900010095
  LPF ALTER_SPELL_HEADER INT_VAR projectile = %IDPRO251% STR_VAR icon = ~ILNCE~ END
  LPF ALTER_EFFECT
      INT_VAR savingthrow = 8           //  save wand
  END      //

//snowball swarm
//Projectile
  ADD_PROJECTILE ~%folder%/data/wands/IDPRO217.pro~   //projectile
//bam
  COPY ~%folder%/data/wands/ssswarh.BAM~ ~override~   //animation icelant  ILNCE
  COPY ~%folder%/data/wands/ssswarr.BAM~ ~override~   //animation icelant
  COPY ~%folder%/data/wands/ssswarx.BAM~ ~override~   //animation icelant
  COPY ~%folder%/data/wands/ssswart.BAM~ ~override~   //animation icelant

//sounds
  COPY ~%folder%/data/wands/TRA_18.WAV~ ~override~   //animation
  COPY ~%folder%/data/wands/RNG_M02.WAV~ ~override~   //animation
//VVC
  COPY ~%folder%/data/wands/#ssswarm.VVC~ ~override~   //


//////Spell Itself (and spell biz (e.g. sec spells)
  COPY ~%folder%/data/wands/B_SSSWM.SPL~ ~override~   //
        SAY NAME1 @900010097     //
        SAY NAME2 @900010097
  LPF ALTER_SPELL_HEADER INT_VAR projectile = %IDPRO217% STR_VAR icon = ~~ END
  LPF ALTER_EFFECT
      INT_VAR savingthrow = 8           //  save wand
  END      //
//sec spells
  COPY ~%folder%/data/wands/B_SSSWMB.SPL~ ~override~   //
  LPF ALTER_EFFECT
      INT_VAR savingthrow = 8           //  save wand
  END      //
  COPY ~%folder%/data/wands/B_SSSWMC.SPL~ ~override~   //
  LPF ALTER_EFFECT
      INT_VAR savingthrow = 8           //  save wand
  END      //

//ice storm  B_I_STO SPWI404.spl
 COPY_EXISTING ~SPWI404.spl~ ~override/B_WANBA.spl~
  LPF ALTER_SPELL_TYPE INT_VAR spell_type = 4 spell_level = 1 END
  LPF ALTER_EFFECT
      INT_VAR savingthrow = 8           //  save wand
  END      //


 LAF tooltips INT_VAR
  $tip(1) = RESOLVE_STR_REF (@900010095) // ice lance
  $tip(2) = RESOLVE_STR_REF (@900010097) // SSS
  $tip(3) = RESOLVE_STR_REF (@900010098) // Ice Storm
 STR_VAR
  item = WANDFRE //
 END


//dummy spells in spells.ids for dlg code if nec (not nec here as ice storm is req to create wand)
// ACTION_IF (!FILE_CONTAINS_EVALUATED(~spell.ids~ ~WIZARD_ACID_STORM~)) BEGIN
//add dummy spell for code
//   APPEND ~spell.ids~ ~5102 WIZARD_ACID_STORM~
// END
// ACTION_IF (!FILE_CONTAINS_EVALUATED(~spell.ids~ ~WIZARD_DEATH_FOG~)) BEGIN
//add dummy spell for code
//   APPEND ~spell.ids~ ~5103 WIZARD_DEATH_FOG~
// END
END


////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////                                    ////////////////////////////////////
////////////////////////////////////          Tier VI Wands             ////////////////////////////////////
////////////////////////////////////                                    ////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////

//___________________________________________________________________________
//
//
//                  Animated Wand
//
//___________________________________________________________________________
//| Animated Wand (N) | VI | Transforms into a blade that fights for the caster |

ACTION_IF NOT FILE_EXISTS_IN_GAME ~B_WAN06.itm~ BEGIN

 COPY ~%folder%/data/wands/B_WAN06.itm~ ~override~
        SAY NAME1 @900010075     //unidentified Wand
        SAY UNIDENTIFIED_DESC @900010076   //unidentified generic desc
        SAY NAME2 @900010011
        SAY DESC @900010012
//cre
 COPY ~%folder%/data/wands/B_WAN06.cre~ ~override~
          SAY NAME1 @900010011
          SAY NAME2 @900010011
//crea weapon  IPSION.itm
 COPY ~%folder%/data/wands/B_WAN06A.itm~ ~override~
          SAY NAME1 @900010011
          SAY NAME2 @900010011
//just in case
 COPY ~%folder%/data/wands/IPSION.itm~ ~override~

END  //end if no animated wand

//___________________________________________________________________________
//
//
//                  Wand of Banishment
//
//___________________________________________________________________________
//| of Banishment (Ns) | VI | Removes summoned creatures, evil outsiders save or destroyed/banished |
//only usable if SR is installed

ACTION_IF NOT FILE_EXISTS_IN_GAME ~B_WAN12.itm~ BEGIN

 ACTION_IF (FILE_CONTAINS_EVALUATED(~spell.ids~ ~CLERIC_BANISHMENT~)) BEGIN  //SR Banishment

 LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~CLERIC_BANISHMENT~
  RET spell_res
 END

 COPY_EXISTING ~%spell_res%.spl~ ~override/B_WANBA.spl~
  WRITE_BYTE 0x001c  4  //innate
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 177 savingthrow = 8           //  save wand
  END      //
  LPF CLONE_EFFECT
      INT_VAR match_opcode = 177 savingthrow = 0  timing = 0 duration = 18
      STR_VAR resource = ~B_WANST~   //Stun
  END

  //stun eff
  COPY ~%folder%/data/wands/B_WANST.eff~ ~override~   //stun effect

  //actual wand
  COPY ~%folder%/data/wands/B_WAN12.itm~ ~override~
        SAY NAME2 @900010023
        SAY DESC @900010024


 END //end check for banishment
//dummy wand if not available
 ACTION_IF (!FILE_CONTAINS_EVALUATED(~spell.ids~ ~CLERIC_BANISHMENT~)) BEGIN

  COPY_EXISTING ~WAND03.ITM~ ~override/B_WAN12.ITM~

//add dummy spell for code
   APPEND ~spell.ids~ ~5101 CLERIC_BANISHMENT~
 END

END//end check for wand

////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////                                    ////////////////////////////////////
////////////////////////////////////         Tier VII Wands             ////////////////////////////////////
////////////////////////////////////                                    ////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////

//___________________________________________________________________________
//
//
//                  Wand of Corrosion
//
//___________________________________________________________________________
//WANDCOR.itm Wand of Corrosion IWDEE only
ACTION_IF !FILE_EXISTS_IN_GAME ~WANDCOR.ITM~ BEGIN  //
  COPY ~%folder%/data/arcane_crafting/wand/WANDCOR.ITM~ ~override~
        SAY NAME1 @900010075     //unidentified Wand
        SAY UNIDENTIFIED_DESC @900010076   //unidentified wand generic desc
        SAY NAME2 @900010070
	SAY DESC @900010071
//Icon
  COPY ~%folder%/data/arcane_crafting/wand/IWANDCOR.bam~ ~override~
//Death Fog
//Projectile
  ADD_PROJECTILE ~%folder%/data/wands/IDPRO212.pro~   //projectile
//bam
  COPY ~%folder%/data/wands/DFOGA.BAM~ ~override~   //animation
  COPY ~%folder%/data/wands/DFOGR.BAM~ ~override~   //animation
  COPY ~%folder%/data/wands/DFOGX.BAM~ ~override~   //animation
  COPY ~%folder%/data/wands/DFOGB.BAM~ ~override~   //animation

//sounds
  COPY ~%folder%/data/wands/ARE_M02.WAV~ ~override~   //animation
  COPY ~%folder%/data/wands/RNG_M01.WAV~ ~override~   //animation

//////Spell Itself (and spell biz (e.g. sec spells)
  COPY ~%folder%/data/wands/B_DFOG.SPL~ ~override~   //
        SAY NAME1 @900010091     //unidentified Wand
        SAY NAME2 @900010091
  LPF ALTER_SPELL_HEADER INT_VAR projectile = %IDPRO212% STR_VAR icon = ~DFOGB~ END
  COPY ~%folder%/data/wands/B_DFOGB.SPL~ ~override~   //
  COPY ~%folder%/data/wands/B_DFOGC.SPL~ ~override~   //

//Acid storm
//Projectile
  ADD_PROJECTILE ~%folder%/data/wands/IDPRO211.pro~   //projectile
//bam
  COPY ~%folder%/data/wands/ASTORMA.BAM~ ~override~   //animation astorma
  COPY ~%folder%/data/wands/ASTORMX.BAM~ ~override~   //animation   astormx
  COPY ~%folder%/data/wands/DACIDS.BAM~ ~override~   //animation
//////Spell Itself (and spell biz (e.g. sec spells)
  COPY ~%folder%/data/wands/B_ACIDS.SPL~ ~override~   //
        SAY NAME1 @900010092     //
        SAY NAME2 @900010092
  LPF ALTER_SPELL_HEADER INT_VAR projectile = %IDPRO211% STR_VAR icon = ~DACIDS~ END

 LAF tooltips INT_VAR
  $tip(1) = RESOLVE_STR_REF (@900010091) // Death Fog
  $tip(2) = RESOLVE_STR_REF (@900010092) // Acid Storm
 STR_VAR
  item = WANDCOR //
 END


//dummy spells in spells.ids for dlg code if nec
 ACTION_IF (!FILE_CONTAINS_EVALUATED(~spell.ids~ ~WIZARD_ACID_STORM~)) BEGIN
//add dummy spell for code
   APPEND ~spell.ids~ ~5102 WIZARD_ACID_STORM~
 END
 ACTION_IF (!FILE_CONTAINS_EVALUATED(~spell.ids~ ~WIZARD_DEATH_FOG~)) BEGIN
//add dummy spell for code
   APPEND ~spell.ids~ ~5103 WIZARD_DEATH_FOG~
 END

END


//CONTINUE
//___________________________________________________________________________
//
//
//                  Wand of Wonder
//
//___________________________________________________________________________
//created w wish spell and only by wild mage
//THIS ONE NEEDS TO BE CHECKED

//WAND12.itm Wand of wonder (in bg2ee as WAND12.itm, but in IWDEE and BGEE is another wand of missles...)

ACTION_IF !GAME_IS ~bg2ee eet~ BEGIN  //
  COPY ~%folder%/data/arcane_crafting/wand/WAND12.ITM~ ~override~
        SAY NAME1 @900010075     //unidentified Wand
        SAY NAME2 @900010073
        SAY UNIDENTIFIED_DESC @900010076   //unidentified generic desc
	SAY DESC @900010074
//Icon
  COPY ~%folder%/data/arcane_crafting/wand/IWAND12.bam~ ~override~
//ADD ANIMATIONS
  COPY ~%folder%/data/arcane_crafting/wand/SPFLSRIN.bam~ ~override~
  COPY ~%folder%/data/arcane_crafting/wand/SPFLESHS.bam~ ~override~
  COPY ~%folder%/data/arcane_crafting/wand/SPARMOUR.bam~ ~override~
  COPY ~%folder%/data/arcane_crafting/wand/SPSTRENI.bam~ ~override~
  COPY ~%folder%/data/arcane_crafting/wand/SPWRDFLD.bam~ ~override~
  COPY ~%folder%/data/arcane_crafting/wand/WONDER.vvc~ ~override~
  COPY ~%folder%/data/arcane_crafting/wand/MAGRES.vvc~ ~override~
  COPY ~%folder%/data/arcane_crafting/wand/ICSTRENI.vvc~ ~override~


  ACTION_IF GAME_IS ~bgee~ THEN BEGIN   //
      COPY_EXISTING ~WAND12.ITM~ ~override~
        LPF ALTER_EFFECT INT_VAR match_opcode = 139 match_parameter1 = 14667  parameter1 = 26019 END //haste notification
        LPF ALTER_EFFECT INT_VAR match_opcode = 139 match_parameter1 = 14042  parameter1 = 26016 END //Strength Modification
        LPF ALTER_EFFECT INT_VAR match_opcode = 139 match_parameter1 = 39326  parameter1 = 25954 END //Stoneskin notification  NOt best option, check gibberlings
  END

  ACTION_IF GAME_IS ~iwdee~ THEN BEGIN   //
      COPY_EXISTING ~WAND12.ITM~ ~override~
        LPF ALTER_EFFECT INT_VAR match_opcode = 139 match_parameter1 = 14667  parameter1 = 14023 END //haste notification
  END

END   //not game is bg2ee



//to do list
////////////////////////////////////////////////////////////////////////
//////////////////            Wand of Mirrors         //////////////////
////////////////////////////////////////////////////////////////////////
//| of Mirrors (N)  | ? |  Shield and Mirror Image |

////////////////////////////////////////////////////////////////////////
//////////////////            Wand of Negation        //////////////////
////////////////////////////////////////////////////////////////////////
//| of Negation (N)  | ? |  Dispel Magic |

////////////////////////////////////////////////////////////////////////
//////////////////            Wand of Peace           //////////////////
////////////////////////////////////////////////////////////////////////
//| of Peace (N) | ? |  All creatures in area save or cannot attack for 3 rounds |

////////////////////////////////////////////////////////////////////////
//////////////////          Wand of Revealing         //////////////////
////////////////////////////////////////////////////////////////////////
//| of Revealing (N)  | ? |  Find Traps/D. Illusion 75% |

////////////////////////////////////////////////////////////////////////
//////////////////             Wand of Salt           //////////////////
////////////////////////////////////////////////////////////////////////
//| of Salt (N) | ? | 6d8 dam plant cre (3d6 non plant) Save for 1/2 |


////////////////////////////////////////////////////////////////////////
//////////////////             Wand of Steam          //////////////////
////////////////////////////////////////////////////////////////////////
//| of Steam (N)  | ? |  As Cloudkill, but fire damage 3 r: 6d6/4d6/2d6 |

////////////////////////////////////////////////////////////////////////
//////////////////            Wand of the Squid       //////////////////
////////////////////////////////////////////////////////////////////////
//| of the Squid (N)  | ? |  4d4 crush and hold (save 1/2 dam, no hold |

////////////////////////////////////////////////////////////////////////
//////////////////            Wand of the Sun         //////////////////
////////////////////////////////////////////////////////////////////////
//| of the Sun (N)  | ? |  Ray 6d4 fire +2d4 metal wearing x2 undead|

////////////////////////////////////////////////////////////////////////
//////////////////            Wand of Traps           //////////////////
////////////////////////////////////////////////////////////////////////
//| of Traps(N)  | ? |   as Find Traps |  Each charge just one 'check'

////////////////////////////////////////////////////////////////////////
//////////////////             Wand of Light          //////////////////
////////////////////////////////////////////////////////////////////////
//| of Light (N)  | VII |  Light Blade; Sun Ray (beam does 2d6+2 magic) x2 undead; Prot from evil; good only |

//Misc notes

//WAND14.itm Web sack??? IN BG2EE , but not in other two?  Monster item???
//Not going to include for now.  Doesn't seem like it's needed

//WAND16.itm and WAND17.itm are 'potions of icedust' in BG2EE...
//Not adding for now








//CONTINUE



//___________________________________________________________________________
//
//
//                  Wand of
//
//___________________________________________________________________________






////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////                                    ////////////////////////////////////
////////////////////////////////////         Tier II Wands              ////////////////////////////////////
////////////////////////////////////                                    ////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////

////////////////////////////////////////////////////////////////////////
//////////////////            Gremlin Wand            //////////////////
////////////////////////////////////////////////////////////////////////

ACTION_IF NOT FILE_EXISTS_IN_GAME ~B_WAN17.ITM~ BEGIN

//| Gremlin Wand (N) | II | Summon Gremlins |
//copy over the monsters:
COPY ~%folder%/data/wands/b_grem01.cre~ ~override~
          SAY NAME1 @900010049
          SAY NAME2 @900010049
//cre item
COPY ~%folder%/data/wands/b_grem01.itm~ ~override~


//copy over the table:
COPY ~%folder%/data/wands/B_GREM.2da~ ~override~

//add to sumtable
LAF cd_new_summon_table STR_VAR descript = "GREMLINS" 2da_file = B_GREM RET table END

//add the wand and ref sumtable

COPY ~%folder%/data/wands/B_WAN17.itm~ ~override~
          SAY NAME2 @900010033
          SAY DESC @900010034
  LPF ALTER_EFFECT INT_VAR match_opcode = 331 parameter2 = table END

END  //end gremlin wand

////////////////////////////////////////////////////////////////////////
//////////////////           Wand of Illusion         //////////////////
////////////////////////////////////////////////////////////////////////
//| of Illusion (N) | II |  Glammer; Ph. Force |



////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////                                    ////////////////////////////////////
////////////////////////////////////         Tier III Wands             ////////////////////////////////////
////////////////////////////////////                                    ////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////




////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////                                    ////////////////////////////////////
////////////////////////////////////          Tier IV Wands             ////////////////////////////////////
////////////////////////////////////                                    ////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////






////////////////////////////////////////////////////////////////////////
//////////////////         Wand of Healing            //////////////////
////////////////////////////////////////////////////////////////////////

//| of Healing (N)  | ? |  Cure 2d6+2 HP at range |

ACTION_IF NOT FILE_EXISTS_IN_GAME ~B_WAN13.ITM~ BEGIN
  COPY ~%folder%/data/wands/B_WAN13.itm~ ~override~
        SAY NAME2 @900010023
        SAY DESC @900010024
END
////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////                                    ////////////////////////////////////
////////////////////////////////////          Tier V Wands              ////////////////////////////////////
////////////////////////////////////                                    ////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////

////////////////////////////////////////////////////////////////////////
//////////////////         Wand of Cloudkill          //////////////////
////////////////////////////////////////////////////////////////////////
ACTION_IF NOT FILE_EXISTS_IN_GAME ~IWAND13.BAM~ BEGIN

  COPY ~%folder%/data/arcane_crafting/wand/IWAND13.BAM~ ~override~

END


ACTION_IF NOT FILE_EXISTS_IN_GAME ~WAND13.ITM~ BEGIN

  COPY ~%folder%/data/arcane_crafting/wand/WAND13.ITM~ ~override~
        SAY NAME1 @900010055
        SAY NAME2 @900010068
	SAY DESC @900010069
        SAY UNIDENTIFIED_DESC @900010058

END






////////////////////////////////////////////////////////////////////////
//////////////////          Wand of Swarming          //////////////////
////////////////////////////////////////////////////////////////////////
//| of Swarming (N)  | ? |  as Summon Insects |
ACTION_IF NOT FILE_EXISTS_IN_GAME ~B_WAN15.itm~ BEGIN

  COPY ~%folder%/data/wands/B_WAN15.itm~ ~override~
        SAY NAME2 @900010029
        SAY DESC @900010030

END

////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////                                    ////////////////////////////////////
////////////////////////////////////          Tier VI Wands             ////////////////////////////////////
////////////////////////////////////                                    ////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////

////////////////////////////////////////////////////////////////////////
//////////////////      Wand of Spell Striking        //////////////////
////////////////////////////////////////////////////////////////////////

ACTION_IF NOT FILE_EXISTS_IN_GAME ~WAND18.itm~ BEGIN
  COPY ~%folder%/data/arcane_crafting/wand/IWAND18.bam~ ~override~
  COPY ~%folder%/data/arcane_crafting/wand/WAND18.ITM~ ~override~
        SAY NAME1 @68077
        SAY NAME2 @68083
        SAY UNIDENTIFIED_DESC @68080
	SAY DESC @68084
  LPF ALTER_EFFECT INT_VAR STR_VAR match_resource = SPWI513 resource = B_WA101 END      //   breach
  LPF ALTER_EFFECT INT_VAR STR_VAR match_resource = SPWI608 resource = B_WA102 END      // sp piercing

//tooltip
LAF tooltips INT_VAR
  $tip(1) = RESOLVE_STR_REF (@68085) // Breach
  $tip(2) = RESOLVE_STR_REF (@68086) // Pierce Magic
STR_VAR
  item = WAND18 // file name
END
//spells
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~WIZARD_BREACH~
  RET spell_res
END
  COPY_EXISTING ~%spell_res%.spl~ ~override/B_WA101.spl~
    LPF ALTER_SPELL_TYPE INT_VAR   spell_type = 4 END

  COPY ~%folder%/data/arcane_crafting/wand/B_WA102.SPL~ ~override~
        SAY NAME1 @68086
        SAY NAME2 @68086
        LPF ALTER_EFFECT INT_VAR match_opcode = 139 parameter1 = RESOLVE_STR_REF (@68087) STR_VAR END  //Spell Protections Removed

  COPY ~%folder%/data/arcane_crafting/wand/SPATTCK1.BAM~ ~override~

END  //end add wand

////////////////////////////////////////////////////////////////////////
//////////////////          Wand of Cursing           //////////////////
////////////////////////////////////////////////////////////////////////

//
ACTION_IF NOT FILE_EXISTS_IN_GAME ~WAND19.itm~ BEGIN
  COPY ~%folder%/data/arcane_crafting/wand/IWAND19.bam~ ~override~

  COPY ~%folder%/data/arcane_crafting/wand/WAND19.ITM~ ~override~
        SAY NAME1 @68077
        SAY NAME2 @68078
        SAY UNIDENTIFIED_DESC @68080
	SAY DESC @68079
  LPF ALTER_EFFECT INT_VAR match_opcode = 139 parameter1 = RESOLVE_STR_REF (@68081) match_parameter1 = 37800 STR_VAR END  //blind notification
  LPF ALTER_EFFECT INT_VAR match_opcode = 139 parameter1 = RESOLVE_STR_REF (@68082) match_parameter1 = 35952 STR_VAR END  //deaf notification
  LPF ALTER_EFFECT INT_VAR match_opcode = 139 parameter1 = RESOLVE_STR_REF (@68083) match_parameter1 = 37805 STR_VAR END  //Silence notification
END  //end add wand







////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////                                    ////////////////////////////////////
////////////////////////////////////          Tier VII Wands            ////////////////////////////////////
////////////////////////////////////                                    ////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////

////////////////////////////////////////////////////////////////////////
//////////////////          Wand of Command           //////////////////
////////////////////////////////////////////////////////////////////////
//| of Command (N)  | VII |  as Dominate |

  COPY ~%folder%/data/wands/B_WAN04.itm~ ~override~
        SAY NAME2 @900010007
        SAY DESC @900010008

//text notification (BG2EE/EET is the default)
  ACTION_IF GAME_IS ~bgee~ BEGIN

  COPY_EXISTING ~B_WAN04.itm~ ~override~
   LPF ALTER_EFFECT
      INT_VAR match_opcode = 139            //
      parameter1 = 26206
  END      //

  END
  ACTION_IF GAME_IS ~iwdee~ BEGIN

  COPY_EXISTING ~B_WAN04.itm~ ~override~
   LPF ALTER_EFFECT
      INT_VAR match_opcode = 139            //
      parameter1 = 35544
   END      //

  END


////////////////////////////////////////////////////////////////////////
//////////////////        Wand of the Heavens         //////////////////
////////////////////////////////////////////////////////////////////////
ACTION_IF NOT FILE_EXISTS_IN_GAME ~TTWAND.ITM~ BEGIN

  COPY_EXISTING ~WAND11.ITM~ ~override/TTWAND.ITM~

END

////////////////////////////////////////////////////////////////////////
//////////////////           Wand of Death            //////////////////
////////////////////////////////////////////////////////////////////////
//| of Death (N) | VII | Death Spell? |

ACTION_IF NOT FILE_EXISTS_IN_GAME ~B_WAN16.ITM~ BEGIN

  COPY ~%folder%/data/wands/B_WAN16.itm~ ~override~
        SAY NAME2 @900010031
        SAY DESC @900010032

END

////////////////////////////////////////////////////////////////////////
//////////////////           Wand of Darkness         //////////////////
////////////////////////////////////////////////////////////////////////

ACTION_IF NOT FILE_EXISTS_IN_GAME ~B_WAN18.ITM~ BEGIN

  COPY ~%folder%/data/wands/B_WAN18.itm~ ~override~
        SAY NAME2 @900010035
        SAY DESC @900010036

//tooltip
 LAF tooltips INT_VAR
  $tip(1) = RESOLVE_STR_REF (@900010041) // Blindness
  $tip(2) = RESOLVE_STR_REF (@900010042) // Smite Good
  $tip(3) = RESOLVE_STR_REF (@900010043) // Summon Shadow
 STR_VAR
  item = B_WAN18 // file name
 END

END

*/